## Copyright 2009-2021 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OSPRAY_VER: "2.6.0"
  RKCOMMON_VER: "1.6.1"

stages:
  - build
  - test
  - release
  - scan

.build-linux:
  stage: build
  needs: []
  tags: [docker]

source-protex-scan:
  stage: scan
  image: amd64/openjdk:8
  script:
    - gitlab/source-scan-protex.sh
  tags: [docker]
  needs: []
  allow_failure: true

########
# These build phases will no longer work on current branches, due to non-release branch dependencies
########
build-ubuntu18.04:
  extends: .build-linux
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  script:
    - gitlab/build.sh
  artifacts:
    name: ospray-studio
    paths:
      - build/
  only:
    - master
    - /^release-.*$/

build-osx-clang:
  stage: build
  tags: [osx, clang]
  script:
    - gitlab/macos.sh
  artifacts:
    name: ospray-studio
    paths:
      - build-macos/
  only:
    - master
    - /^release-.*$/

build-windows-msvc15:
  stage: build
  tags: [win, msvc15]
  script:
    - gitlab\win.ps1
  artifacts:
    name: ospray-studio
    paths:
      - build-win/
  only:
    - master
    - /^release-.*$/

build-kw:
  extends: .build-linux
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  script:
    - gitlab/build-kw.sh
  artifacts:
    paths:
      - klocwork/*
  only:
    - master
    - /^release-.*$/

test-run-ubuntu18.04:
  stage: test
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  needs: [build-ubuntu18.04]
  tags: [docker]
  script:
    - gitlab/run.sh
  only:
    - master
    - /^release-.*$/

test-kw:
  stage: scan
  tags: [docker]
  image: $DOCKER_REGISTRY/ospray/docker-images:centos7
  needs: [build-kw]
  script:
    - gitlab/kw-check-issues.sh
  allow_failure: true
  only:
    - master
    - /^release-.*$/

########
# Transitional phases, only works against devel branch dependencies
########

build-ubuntu18.04-dev:
  extends: .build-linux
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  script:
    - gitlab/build-dev.sh
  artifacts:
    name: ospray-studio
    paths:
      - build

build-osx-clang-dev:
  stage: build
  tags: [osx, clang]
  script:
    - gitlab/macos-dev.sh
  artifacts:
    name: ospray-studio
    paths:
      - build-macos

build-windows-msvc15-dev:
  stage: build
  tags: [win, msvc15]
  script:
    - gitlab\win-dev.ps1
  artifacts:
    name: ospray-studio
    paths:
      - build-win

build-kw-dev:
  extends: .build-linux
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  script:
    - gitlab/build-kw-dev.sh
  artifacts:
    paths:
      - klocwork/*

test-kw-dev:
  stage: scan
  tags: [docker]
  image: $DOCKER_REGISTRY/ospray/docker-images:centos7
  needs: [build-kw-dev]
  script:
    - gitlab/kw-check-issues.sh
  allow_failure: true

kw-gen-report:
  stage: scan
  tags: [docker]
  image: $DOCKER_REGISTRY/ospray/docker-images:centos7
  needs: [build-kw-dev]
  script:
    - gitlab/kw-gen-report.sh
  artifacts:
    paths:
      - klocwork/report.log


test-run-ubuntu18.04-dev:
  stage: test
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  needs: [build-ubuntu18.04-dev]
  tags: [docker]
  script:
    - gitlab/run-dev.sh

release-linux:
  stage: release
  image: $DOCKER_REGISTRY/ospray/docker-images:ubuntu18.04-mod-test
  dependencies: []
  tags: [docker]
  script:
   - gitlab/build.sh package
  artifacts:
    name: ospray_studio
    paths:
      - build/package/ospray_studio*

release-windows:
  stage: release
  dependencies: []
  tags:
    - msvc15
    - win
  script:
    - gitlab\win.ps1 package
  artifacts:
    name: ospray_studio
    paths:
      - build-win/package/ospray_studio*

release-macos:
  stage: release
  dependencies: []
  tags:
    - osx
    - clang
    - sign
  script:
   - gitlab/macos.sh package
  artifacts:
    name: ospray_studio
    paths:
      - build-macos/package/ospray_studio*

scan-bdba-bin:
  stage: scan
  image: $DOCKER_REGISTRY/ospray/docker-images:centos7
  tags: [docker]
  needs: [release-linux, release-windows, release-macos]
  script:
    - gitlab/bdba.sh "build*/package/ospray_studio*"
    - gitlab/store-files.sh $CI_PROJECT_NAME $CI_PIPELINE_ID bdba "ospray_studio*.pdf"
    - gitlab/store-files.sh $CI_PROJECT_NAME $CI_PIPELINE_ID bdba "ospray_studio*.csv"
  artifacts:
    paths:
      - ospray_studio*.pdf
      - ospray_studio*.csv

av:
  stage: scan
  tags: [docker]
  image: $DOCKER_REGISTRY/clamav:ubuntu20.04
  needs: [release-linux, release-windows, release-macos]
  script:
    - freshclam | tee -a /tmp/av_scan.log
    - clamscan -va --max-filesize=512M --max-scansize=2048M --alert-broken --alert-exceeds-max build*/package/ospray_studio* | tee -a /tmp/av_scan.log
    - gitlab/store-files.sh $CI_PROJECT_NAME $CI_PIPELINE_ID av /tmp/av_scan.log

