
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      cache-dir:
        required: true
        type: string
      # artifact-out:
      #   required: false
      #   type: string
      runs-on:
        required: false
        type: string
        default: '[ "Linux", "build" ]'

env:
  CACHE_DIR: ${{ inputs.cache-dir }}
  OSPRAY_VER: devel
  RKCOMMON_VER: devel

defaults:
  run:
    shell: bash

jobs:
  exec:

    runs-on: ${{ fromJSON(inputs.runs-on) }}

    container:
      image: amr-registry.caas.intel.com/renderkit/${{ inputs.image }}
      options: --user root
      volumes:
        - /NAS:/NAS

    steps:

      # - name: Checkout
      #   uses: actions/checkout@v3
      
      - name: Checkout dependencies
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SDVIS_DEVOPS_PAT }}
          repository: intel-innersource/libraries.graphics.renderkit.ospray
          ref: devel
          path: ospray-${{ env.OSPRAY_VER }}

      - name: Cache OSPRay
        run: |
          if [[ ! -d "$CACHE_DIR/ospray-$OSPRAY_VER" ]]
          then
            cmake -L -S ./scripts/superbuild -B ospray-$OSPRAY_VER -DBUILD_OIDN=ON -DBUILD_EMBREE_FROM_SOURCE=OFF -DBUILD_RKCOMMON_VERSION=$RKCOMMON_VER -DINSTALL_IN_SEPARATE_DIRECTORIES=OFF
            cmake --build ospray-$OSPRAY_VER
            cp -r ospray-$OSPRAY_VER $CACHE_DIR
          fi

      # - name: Configure dependencies
      #   run: |
      #     cmake -L -S ospray-$OSPRAY_VER/scripts/superbuild -B ospray-$OSPRAY_VER/build -DBUILD_OIDN=ON -DBUILD_EMBREE_FROM_SOURCE=OFF -DBUILD_RKCOMMON_VERSION=$RKCOMMON_VER -DINSTALL_IN_SEPARATE_DIRECTORIES=OFF

      # - name: Build dependencies
      #   run: |
      #     cmake --build ospray-$OSPRAY_VER/build

      # - name: Configure
      #   run: |
      #     export CMAKE_PREFIX_PATH="ospray-$OSPRAY_VER/build/install"
      #     export TBB_ROOT="ospray-$OSPRAY_VER/build/tbb/src/tbb"
      #     cmake -L -S . -B build -DENABLE_OPENIMAGEIO=OFF -DENABLE_OPENVDB=OFF -DENABLE_EXR=OFF

      # - name: Build
      #   run: |
      #     cmake --build build

      # - name: Upload artifact
      #   uses: intel-innersource/libraries.devops.renderkit.actions/upload-artifact@main
      #   with:
      #     name: ${{ inputs.artifact-out }}
      #     path: build ospray-devel

